### PR TITLE
Add search bar

### PR DESCRIPTION
**Pull request by Krafalski**
Hello,

I really like your project. I added a search bar. I wasn't sure how to connect the file `/public/search.js` correctly, since I only ran the front end (I didn't use the server - it kept timing out). I followed the pattern you had in your index.html. 

Let me know if you would like me to make any changes.

### CODE REVIEW

**Comment by Tanza3D** [comment]
not sure what you've done here but it's really messed up the styling, i'll try to fix it and merge this

**Comment by Krafalski** [comment]
@Tanza3D Oh no! I'm not sure what went wrong. I added a form in the `.amount` div in `index.html`

As far as style, the end result looked like this (search bar in the `.amount` div

Screenshot 2023-06-11 at 7 17 30 AM

To accomplish this, I changed the following css:

```css
.amount {
  display: flex;
  justify-content: space-around;
}

.filtered {
  display: none;
}
```

I hope that is helpful. I can make updates on my end.

**Comment by Tanza3D** [comment]
added at https://github.com/Tanza3D/reddark/commit/579cf220711d99622141fc12ad99ab096e85106e 
(used your code, just did this to save git conflict hastle)

**Comment by Krafalski** [comment]
I think the updates you made to the appearance look great.

I am sorry that my code couldn’t be merged in as I don’t show up as a contributor. 

Thank you for reviewing my code.

**Comment by Tanza3D** [comment]
sorry about that, i left a comment in the code crediting you atleast

**Comment by Krafalski** [comment]
Thank you, it is appreciated.On Jun 11, 2023, at 09:25, Tanza ***@***.***> wrote:﻿
sorry about that, i left a comment in the code crediting you atleast

**Pull request closed without merging**
