### PR TITLE
added explanation about subreddit list source

### PR DESCRIPTION
**Pull request by username-is-required**
imo it would be worth having a brief explanation in the readme about where the subreddit list comes from, in case any mods see the site and their subreddits aren’t on it.

### CODE REVIEW

**Comment by Tanza3D** [comment]
i also want to add a way to have our own third party list, there are loads of subreddits i've seen which are participating but aren't on the list, so maybe a google form to submit missing ones would be nice to add there after (and if) i get that working too

**Comment by Tanza3D** [comment]
oh this is a PR, lmao, i'm tired, yeah looks good

**Comment by username-is-required** [comment]
> i also want to add a way to have our own third party list, there are loads of subreddits i've seen which are participating but aren't on the list

at the risk of being annoying, i’d suggest that it would be good to - as far as possible - keep the r/modcoord lists as a single point of truth. i’m just imaging that otherwise, having multiple third party lists would make things harder to coordinate if someone is trying to work from (or create) an accurate list of participating subreddits.

sorry if i’m suggesting something you’ve already done, but have you sent a modmail to r/modcoord with the ones you’ve seen that aren’t on the threads right now? if not, that might be worth trying to see if they’ll add them.

**Comment by Tanza3D** [comment]
not yet, but probably would be worth doing

**Pull request merged**
